export const UPLOAD_PRODUCT_IMAGE_URL_PATH = '/product/202309/images/upload';,export const UPLOAD_PRODUCT_IMAGE_METHOD = '1';


/**
 * 接口名称：Upload Product Image
 * 接口标识：Upload Product Image
 * 接口使用场景：Upload Product Image
 **/
export interface UploadProductImageRequestInterface {
  /**
   * @description: Image file data to be uploaded to Tiktok Shop. The picture file is a string generated by binary.<br>Prerequisites：<br>- image formats support JPG, JPEG, PNG<br>- image pixels at least 100 * 100 and at most 20000 * 20000<br>- Max size of original image: 5MB
   * @type: file
   **/
  data: file;

  /**
   * @description: By specifying the usage scenario of the image during the upload process with different parameters, the image will be processed into different sizes to meet the listing requirements.<br>The usage scenarios include:<br>MAIN_IMAGE: Aspect ratios exceeding 3:4-4:3 will be cropped to fit within the range of 3:4-4:3.<br>ATTRIBUTE_IMAGE:Aspect ratios exceeding 3:4-4:3 will be cropped to fit within the range of 3:4-4:3.<br>DESCRIPTION_IMAGE：Keep the original image returned after uploading.<br>CERTIFICATION_IMAGE：Keep the original image returned after uploading.<br>SIZE_CHART_IMAGE：Keep the original image returned after uploading.
   * @type: string
   **/
  use_case?: string;
}


/**
 * 接口名称：Upload Product Image
 * 接口标识：Upload Product Image
 * 接口使用场景：Upload Product Image
 **/
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface UploadProductImageRequestInterface {

}


/**
 * 接口名称：Upload Product Image
 * 接口标识：Upload Product Image
 * 接口使用场景：Upload Product Image
 **/
export interface UploadProductImageResponseInterface {
  /**
   * @description: The success or failure status code returned in API response.
   * @type: int
   **/
  code?: int;

  /**
   * @description: The success or failure messages returned in API response. Reasons of failure will be described in the message.
   * @type: string
   **/
  message?: string;

  /**
   * @description: Request log
   * @type: string
   **/
  request_id?: string;

  /**
   * @description: Specific return information
   * @type: object
   **/
  data?: object;
}


/**
 * @description Specific return information
 **/
export interface UploadProductImageDataResponseInterface {
  /**
   * @description: The URI returned from uploading the image, which can be used for product main image, SKU image, size chart image, qualification image, etc. when listing a product.
   * @type: string
   **/
  ^uri?: string;

  /**
   * @description: The URL returned from uploading the image can be directly opened in a browser. It can be used in product description when creating a product.
   * @type: string
   **/
  ^url?: string;

  /**
   * @description: Height dimension of the image which is determined on upload. This is the height post processing.
   * @type: int
   **/
  ^height?: int;

  /**
   * @description: Width dimension of the image which is determined on upload. This is the width of post processing.
   * @type: int
   **/
  ^width?: int;

  /**
   * @description: Return the usage scenario provided during the upload.<br>The usage scenarios include:<br>MAIN_IMAGE<br>DESCRIPTION_IMAGE<br>ATTRIBUTE_IMAGE<br>CERTIFICATION_IMAGE<br>SIZE_CHART_IMAGE
   * @type: string
   **/
  ^use_case?: string;
}
