export const UPLOAD_PRODUCT_FILE_URL_PATH = '/product/202309/files/upload';,export const UPLOAD_PRODUCT_FILE_METHOD = '1';


/**
 * 接口名称：Upload Product File
 * 接口标识：Upload Product File
 * 接口使用场景：Upload Product File
 **/
export interface UploadProductFileRequestInterface {
  /**
   * @description: Video or PDF file data to be uploaded to Tiktok Shop. The file is a string generated by binary.<br><br>Prerequisites：<br>- file formats support PDF、video formats support MP4<br>- Max size of original file: 10MB<br>- The video aspect ratio is between 9:16 and 16:9.
   * @type: file
   **/
  data: file;

  /**
   * @description: Name of the uploaded file or video, the file name needs to include the file type.<br>file type extension, such as .PDF<br>
   * @type: string
   **/
  name: string;
}


/**
 * 接口名称：Upload Product File
 * 接口标识：Upload Product File
 * 接口使用场景：Upload Product File
 **/
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface UploadProductFileRequestInterface {

}


/**
 * 接口名称：Upload Product File
 * 接口标识：Upload Product File
 * 接口使用场景：Upload Product File
 **/
export interface UploadProductFileResponseInterface {
  /**
   * @description: The success or failure status code returned in API response.
   * @type: int
   **/
  code?: int;

  /**
   * @description: The success or failure messages returned in API response. Reasons of failure will be described in the message.
   * @type: string
   **/
  message?: string;

  /**
   * @description: Request log
   * @type: string
   **/
  request_id?: string;

  /**
   * @description: Specific return information
   * @type: object
   **/
  data?: object;
}


/**
 * @description Specific return information
 **/
export interface UploadProductFileDataResponseInterface {
  /**
   * @description: The file or video id returned from uploading the file, which can be used for product certification or product video when listing a product.
   * @type: string
   **/
  ^id?: string;

  /**
   * @description: The location of the file. This location can be directly accessed in a browser.
   * @type: string
   **/
  ^url?: string;

  /**
   * @description: The name of video or file.
   * @type: string
   **/
  ^name?: string;

  /**
   * @description: The format of file you uploaded<br>- file formats including PDF、video formats support MP4
   * @type: string
   **/
  ^format?: string;
}
