export const GET_WITHDRAWALS_URL_PATH = '/finance/202309/withdrawals';,export const GET_WITHDRAWALS_METHOD = '2';


/**
 * 接口名称：Get Withdrawals
 * 接口标识：Get Withdrawals
 * 接口使用场景：Get Withdrawals
 **/
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface GetWithdrawalsRequestInterface {

}


/**
 * 接口名称：Get Withdrawals
 * 接口标识：Get Withdrawals
 * 接口使用场景：Get Withdrawals
 **/
export interface GetWithdrawalsRequestInterface {
  /**
   * @description: Use this property to pass shop information in requesting the API. Failure in passing the correct value when requesting the API for cross-border shops will return incorrect response. <br> Get by API [Get Authorization Shop](https://partner.tiktokshop.com/docv2/page/6507ead7b99d5302be949ba9?external_id=6507ead7b99d5302be949ba9)
   * @type: string
   **/
  shop_cipher: string;

  /**
   * @description: Unix timestamp representing the end of transactions time range one wants to request
   * @type: int
   **/
  create_time_lt?: int;

  /**
   * @description: The type of transaction.<br>Possible values:<br>- WITHDRAW：The action of the seller to receive the settlement amount to the bank card through the action of withdrawal<br>- SETTLE：The platform settles the amount to the seller<br>- TRANSFER：Platform subsidies or deductions due to platform policies<br>- REVERSE：Withdrawal failure due to incorrect bank card 
   * @type: string[]
   **/
  types: string[];

  /**
   * @description: The default is 20, it must be positive integer,the range is 1-100
   * @type: int
   **/
  page_size?: int;

  /**
   * @description: The next page token
   * @type: string
   **/
  page_token?: string;

  /**
   * @description: Unix timestamp representing the start of transactions time range one wants to request
   * @type: int
   **/
  create_time_ge?: int;
}


/**
 * 接口名称：Get Withdrawals
 * 接口标识：Get Withdrawals
 * 接口使用场景：Get Withdrawals
 **/
export interface GetWithdrawalsResponseInterface {
  /**
   * @description: The success or failure status code returned in API response.
   * @type: int
   **/
  code?: int;

  /**
   * @description: The success or failure messages returned in API response. Reasons of failure will be described in the message.
   * @type: string
   **/
  message?: string;

  /**
   * @description: Request log
   * @type: string
   **/
  request_id?: string;

  /**
   * @description: Specific return information
   * @type: object
   **/
  data?: object;
}


/**
 * @description Specific return information
 **/
export interface GetWithdrawalsDataResponseInterface {
  /**
   * @description: Cursor used for searching for more information<br>
   * @type: string
   **/
  ^next_page_token?: string;

  /**
   * @description: The total num of the withdraws
   * @type: int
   **/
  ^total_count?: int;

  /**
   * @description: Withdraw list
   * @type: []object
   **/
  ^withdrawals?: []object;
}


/**
 * @description Withdraw list
 **/
export interface GetWithdrawalsDataWithdrawalsResponseInterface {
  /**
   * @description: A unique transaction id generated by TTS for the withdrawal.
   * @type: string
   **/
  ^^id?: string;

  /**
   * @description: WITHDRAW：The action of the seller to receive the settlement amount to the bank card through the action of withdrawal<br>SETTLE：The platform settles the amount to the seller<br>TRANSFER：Platform subsidies or deductions due to platform policies<br>REVERSE：Withdrawal failure due to incorrect bank card 
   * @type: string
   **/
  ^^type?: string;

  /**
   * @description: Withdraw amount
   * @type: string
   **/
  ^^amount?: string;

  /**
   * @description: The three-digit currency code in ISO 4217 format.   
   * @type: string
   **/
  ^^currency?: string;

  /**
   * @description: The processing status of the withdrawal indicates whether the withdrawal is transferred. Possible values:<br>- PROCESSING：the withdrawal is currently processing. If the withdrawal is successful, the status will transition to PAID. If not, it will be FAILED.<br>- SUCCESS：the withdrawal has been transferred to the Seller<br>- FAILED：the withdrawal failed
   * @type: string
   **/
  ^^status?: string;

  /**
   * @description: Withdraw create time
   * @type: int
   **/
  ^^create_time?: int;
}
