export const FULFILLMENT_UPLOAD_DELIVERY_IMAGE_URL_PATH = '/fulfillment/202309/images/upload';,export const FULFILLMENT_UPLOAD_DELIVERY_IMAGE_METHOD = '1';


/**
 * 接口名称：Fulfillment Upload Delivery Image
 * 接口标识：Fulfillment Upload Delivery Image
 * 接口使用场景：Fulfillment Upload Delivery Image
 **/
export interface FulfillmentUploadDeliveryImageRequestInterface {
  /**
   * @description: Image file data to be uploaded to Tiktok Shop. The picture file is a string generated by base64 encoding.<br>Prerequisites：<br>Image formats support JPG, JPEG, PNG<br>Image pixels at least 100 * 100 and at most 20000 * 20000<br>Max size of original image: 5MB
   * @type: file
   **/
  data: file;
}


/**
 * 接口名称：Fulfillment Upload Delivery Image
 * 接口标识：Fulfillment Upload Delivery Image
 * 接口使用场景：Fulfillment Upload Delivery Image
 **/
export interface FulfillmentUploadDeliveryImageRequestInterface {
  /**
   * @description: Use this property to pass shop information in requesting the API. Failure in passing the correct value when requesting the API for cross-border shops will return incorrect response. <br> Get by API [Get Authorization Shop](https://partner.tiktokshop.com/docv2/page/6507ead7b99d5302be949ba9?external_id=6507ead7b99d5302be949ba9)
   * @type: string
   **/
  shop_cipher: string;
}


/**
 * 接口名称：Fulfillment Upload Delivery Image
 * 接口标识：Fulfillment Upload Delivery Image
 * 接口使用场景：Fulfillment Upload Delivery Image
 **/
export interface FulfillmentUploadDeliveryImageResponseInterface {
  /**
   * @description: The success or failure status code returned in API response.
   * @type: int
   **/
  code?: int;

  /**
   * @description: The success or failure messages returned in API response. Reasons of failure will be described in the message.
   * @type: string
   **/
  message?: string;

  /**
   * @description: Request log
   * @type: string
   **/
  request_id?: string;

  /**
   * @description: Specific return information
   * @type: object
   **/
  data?: object;
}


/**
 * @description Specific return information
 **/
export interface FulfillmentUploadDeliveryImageDataResponseInterface {
  /**
   * @description: The URL returned from uploading the image can be directly opened in a browser. 
   * @type: string
   **/
  ^url?: string;

  /**
   * @description: The image length returned from uploading the image is the length of the image after processing based on the usage scenario you provided, to meet the requirements for updating delivery status. This length refers to the processed image length, not the original image length.
   * @type: int
   **/
  ^height?: int;

  /**
   * @description: The image width.
   * @type: int
   **/
  ^width?: int;
}
